In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
my_data=pd.read_csv("C:/Users/Administrator/.ipynb_checkpoints/Admission_Predict.csv")

In [5]:
my_data

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
395         396        324          110                  3  3.5   3.5  9.04   
396         397        325          107                  3  3.0   3.5  9.11   
397         398        330          116                  4  5.0   4.5  9.45   
398         399        312          103                  3  3.5   4.0  8.78   
399         400        333          117                  4  5.0   4.0  9.66   

    Research  Chance of Admit   
0        Yes              0.92  
1        Yes              0.76  
2        Yes              0.72  
3        Yes              0.80  
4         No              0.65  
..       ...               ...  
395      Yes              0.82  
396      Yes              0.84  
397      Yes              0.91  
398       No              0.67  
399      Yes              0.95  

[400 rows x 9 columns]

In [186]:
x1=my_data.iloc[:,1:6].values
y1=my_data.iloc[:,-1].values


In [188]:
x1

array([[337. , 118. ,   4. ,   4.5,   4.5],
       [324. , 107. ,   4. ,   4. ,   4.5],
       [316. , 104. ,   3. ,   3. ,   3.5],
       ...,
       [330. , 116. ,   4. ,   5. ,   4.5],
       [312. , 103. ,   3. ,   3.5,   4. ],
       [333. , 117. ,   4. ,   5. ,   4. ]])

In [190]:
y1

array([0.92, 0.76, 0.72, 0.8 , 0.65, 0.9 , 0.75, 0.68, 0.5 , 0.45, 0.52,
       0.84, 0.78, 0.62, 0.61, 0.54, 0.66, 0.65, 0.63, 0.62, 0.64, 0.7 ,
       0.94, 0.95, 0.97, 0.94, 0.76, 0.44, 0.46, 0.54, 0.65, 0.74, 0.91,
       0.9 , 0.94, 0.88, 0.64, 0.58, 0.52, 0.48, 0.46, 0.49, 0.53, 0.87,
       0.91, 0.88, 0.86, 0.89, 0.82, 0.78, 0.76, 0.56, 0.78, 0.72, 0.7 ,
       0.64, 0.64, 0.46, 0.36, 0.42, 0.48, 0.47, 0.54, 0.56, 0.52, 0.55,
       0.61, 0.57, 0.68, 0.78, 0.94, 0.96, 0.93, 0.84, 0.74, 0.72, 0.74,
       0.64, 0.44, 0.46, 0.5 , 0.96, 0.92, 0.92, 0.94, 0.76, 0.72, 0.66,
       0.64, 0.74, 0.64, 0.38, 0.34, 0.44, 0.36, 0.42, 0.48, 0.86, 0.9 ,
       0.79, 0.71, 0.64, 0.62, 0.57, 0.74, 0.69, 0.87, 0.91, 0.93, 0.68,
       0.61, 0.69, 0.62, 0.72, 0.59, 0.66, 0.56, 0.45, 0.47, 0.71, 0.94,
       0.94, 0.57, 0.61, 0.57, 0.64, 0.85, 0.78, 0.84, 0.92, 0.96, 0.77,
       0.71, 0.79, 0.89, 0.82, 0.76, 0.71, 0.8 , 0.78, 0.84, 0.9 , 0.92,
       0.97, 0.8 , 0.81, 0.75, 0.83, 0.96, 0.79, 0.

In [192]:
from sklearn.model_selection import train_test_split

In [194]:
x1_train,x1_test,y1_train,y1_test=train_test_split(x1,y1,test_size=0.2,random_state=0)

In [196]:
x1_test

array([[309. , 105. ,   5. ,   3.5,   3.5],
       [308. , 110. ,   4. ,   3.5,   3. ],
       [326. , 110. ,   3. ,   3.5,   3.5],
       [306. , 105. ,   2. ,   3. ,   2.5],
       [316. , 105. ,   3. ,   3. ,   3.5],
       [309. , 100. ,   2. ,   3. ,   3. ],
       [312. , 109. ,   3. ,   3. ,   3. ],
       [312. , 104. ,   3. ,   3.5,   4. ],
       [332. , 118. ,   2. ,   4.5,   3.5],
       [331. , 117. ,   4. ,   4.5,   5. ],
       [300. , 105. ,   1. ,   1. ,   2. ],
       [333. , 113. ,   5. ,   4. ,   4. ],
       [320. , 110. ,   2. ,   4. ,   3.5],
       [302. ,  99. ,   1. ,   2. ,   2. ],
       [328. , 112. ,   4. ,   4. ,   4.5],
       [311. , 104. ,   2. ,   2. ,   2. ],
       [312. ,  98. ,   1. ,   3.5,   3. ],
       [329. , 110. ,   2. ,   4. ,   3. ],
       [315. ,  99. ,   2. ,   3.5,   3. ],
       [313. , 107. ,   3. ,   4. ,   4.5],
       [329. , 119. ,   4. ,   4.5,   4.5],
       [327. , 113. ,   4. ,   4.5,   5. ],
       [301. , 106. ,   4. ,   2

In [198]:
y1_test

array([0.71, 0.7 , 0.79, 0.73, 0.72, 0.48, 0.77, 0.71, 0.9 , 0.94, 0.58,
       0.89, 0.72, 0.57, 0.78, 0.42, 0.64, 0.84, 0.63, 0.72, 0.9 , 0.83,
       0.57, 0.47, 0.85, 0.67, 0.44, 0.54, 0.92, 0.62, 0.68, 0.73, 0.73,
       0.61, 0.55, 0.74, 0.64, 0.89, 0.73, 0.95, 0.71, 0.72, 0.75, 0.76,
       0.86, 0.7 , 0.39, 0.79, 0.61, 0.64, 0.71, 0.8 , 0.61, 0.89, 0.68,
       0.79, 0.78, 0.52, 0.76, 0.88, 0.74, 0.49, 0.65, 0.59, 0.87, 0.89,
       0.81, 0.9 , 0.8 , 0.76, 0.68, 0.87, 0.68, 0.64, 0.91, 0.61, 0.69,
       0.62, 0.93, 0.43])

In [200]:
from sklearn.linear_model import LinearRegression

In [202]:
ln=LinearRegression()

In [204]:
ln.fit(x1_test,y1_test)

LinearRegression()

In [206]:
ypredict=ln.predict(x1_test)

In [208]:
ypredict

array([0.69728561, 0.72972252, 0.76631539, 0.6374293 , 0.68528559,
       0.60297518, 0.70763735, 0.69465405, 0.88018633, 0.91891026,
       0.55866338, 0.84538728, 0.76441852, 0.52394722, 0.83535861,
       0.59589052, 0.59413319, 0.76503479, 0.61452897, 0.75400099,
       0.92333353, 0.87050084, 0.65126041, 0.47384649, 0.79793521,
       0.60825083, 0.50290054, 0.66780981, 0.91543371, 0.71287099,
       0.61904809, 0.73000833, 0.7567548 , 0.54586619, 0.79096825,
       0.76277306, 0.73265243, 0.83804664, 0.62605899, 0.9077107 ,
       0.72843928, 0.69889121, 0.74876927, 0.7764159 , 0.90191726,
       0.74736641, 0.62620525, 0.78134188, 0.62261707, 0.59596236,
       0.64907894, 0.76798485, 0.58480866, 0.90259475, 0.69736393,
       0.7078494 , 0.84639049, 0.73611836, 0.78516204, 0.82187332,
       0.73319643, 0.44308361, 0.61707482, 0.55040717, 0.82510728,
       0.74967207, 0.71831692, 0.84740905, 0.73257603, 0.6810285 ,
       0.63894986, 0.79514677, 0.75673488, 0.65956032, 0.89104

In [210]:
comparison=pd.DataFrame(x1_test,columns=['GRE Score','TOEFL Score','University Rating','SOP','LOR '])

In [217]:

comparison["AVL_o/p"]=y1_test


In [225]:
comparison["pred_o/p"]=ypredict


In [227]:
comparison

GRE Score  TOEFL Score  University Rating  SOP  LOR   AVL_o/p  pred_o/p
0       309.0        105.0                5.0  3.5   3.5     0.71  0.697286
1       308.0        110.0                4.0  3.5   3.0     0.70  0.729723
2       326.0        110.0                3.0  3.5   3.5     0.79  0.766315
3       306.0        105.0                2.0  3.0   2.5     0.73  0.637429
4       316.0        105.0                3.0  3.0   3.5     0.72  0.685286
..        ...          ...                ...  ...   ...      ...       ...
75      311.0        104.0                3.0  3.5   2.0     0.61  0.639064
76      306.0        103.0                2.0  2.5   3.0     0.69  0.617195
77      313.0        106.0                2.0  2.5   2.0     0.62  0.632768
78      334.0        116.0                4.0  4.0   3.5     0.93  0.859896
79      297.0         96.0                2.0  2.5   1.5     0.43  0.488825

[80 rows x 7 columns]